version: '3.4'

services:
  api:
    image: tipprunde
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - apps/api/.env
    ports:
      - 127.0.0.1:5432:5432
